name: npm publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install-dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm run bootstrap

  publish-to-npm:
    needs: install-dependency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: |
          npm config set registry http://registry.npmjs.org
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - run: |
          git config user.name "liuxy0551"
          git config user.email "liuxy0551@qq.com"

      - run: npm run release
